# Generated by Django 4.0.4 on 2022-06-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_project_id_contributor_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='assignee_user_id',
            new_name='assignee_user',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='author_user_id',
            new_name='author_user',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='project_id',
            new_name='project',
        ),
    ]
