# Generated by Django 4.0.4 on 2022-06-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_assignee_user_id_issue_assignee_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_user_id',
            new_name='author_user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='issue_id',
            new_name='issue',
        ),
    ]
