# Generated by Django 4.0.4 on 2022-06-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_author_user_id_comment_author_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='author_user_id',
            new_name='author_user',
        ),
    ]
